### ISSUE TITLE
Duplicating or Morphing

### ISSUE THREAD

**Issue by O13SC3N3** [kreezxil/Collapsing-Columns#1]
Several blocks from various mods will change or duplicate, seems mostly with same items with different meta strings.

examples like Tinkers seared glass will change to a smelter/or others if you nerd pole jump with placing a block. Tbh this mod does its job well, but even building structures by just jumping up a block to fill in the gap of your build, it prevents it.

**Comment by kreezxil** [comment]
Thank you for your report, I'll look into this further.

**Comment by kreezxil** [comment]
https://github.com/kreezxil/World-of-Dragons/issues/53

I thought I fixed this but it turns out there are other types of blocks I had not accounted for.

**Comment by kreezxil** [comment]
I was calling the code wrong, this is fixed in 1.12.2-3.0.5 plus implemented a new feature to set how high a column is before it is to be treated as a nerd pole.

**Comment by O13SC3N3** [comment]
Awesome
